// Generated by gencpp from file msg_pkg/msg_data.msg
// DO NOT EDIT!


#ifndef MSG_PKG_MESSAGE_MSG_DATA_H
#define MSG_PKG_MESSAGE_MSG_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg_pkg
{
template <class ContainerAllocator>
struct msg_data_
{
  typedef msg_data_<ContainerAllocator> Type;

  msg_data_()
    : data1(0)
    , data2(0)  {
    }
  msg_data_(const ContainerAllocator& _alloc)
    : data1(0)
    , data2(0)  {
  (void)_alloc;
    }



   typedef int32_t _data1_type;
  _data1_type data1;

   typedef int32_t _data2_type;
  _data2_type data2;





  typedef boost::shared_ptr< ::msg_pkg::msg_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_pkg::msg_data_<ContainerAllocator> const> ConstPtr;

}; // struct msg_data_

typedef ::msg_pkg::msg_data_<std::allocator<void> > msg_data;

typedef boost::shared_ptr< ::msg_pkg::msg_data > msg_dataPtr;
typedef boost::shared_ptr< ::msg_pkg::msg_data const> msg_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_pkg::msg_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_pkg::msg_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'msg_pkg': ['/home/chp/ros/tutorial/pub_sub_ws/src/msg_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::msg_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_pkg::msg_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::msg_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_pkg::msg_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::msg_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_pkg::msg_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "974ada69e2d7501b3274b7b8e93825bd";
  }

  static const char* value(const ::msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x974ada69e2d7501bULL;
  static const uint64_t static_value2 = 0x3274b7b8e93825bdULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_pkg/msg_data";
  }

  static const char* value(const ::msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_pkg::msg_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data1\n\
int32 data2\n\
";
  }

  static const char* value(const ::msg_pkg::msg_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_pkg::msg_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data1);
      stream.next(m.data2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msg_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_pkg::msg_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_pkg::msg_data_<ContainerAllocator>& v)
  {
    s << indent << "data1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data1);
    s << indent << "data2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_PKG_MESSAGE_MSG_DATA_H
